asset_dir = "assets/game"
exclude_assets = []
write_dir = "src/shared/assets"

[creator]
type = "user"
id = 8838265327

[codegen]
output_name = "assets"
typescript = true
style = "flat"
strip_extension = false
