asset_dir = "assets"
exclude_assets = []
write_dir = "src/shared"

[creator]
type = "user"
id = 8838265327

[codegen]
output_name = "assets"
typescript = true
style = "nested"
strip_extension = false
