packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@biomejs/biome': ^2.1.3
  '@rbxts/compiler-types': 3.0.0-types.0
  '@rbxts/types': 1.0.867
  roblox-ts: 3.0.0
  typescript: 5.9.2
  '@rbxts/services': ^1.5.5
