name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  CI: true
  HUSKY: 0

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [24]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - uses: raild3x/setup-rokit@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: License
        run: pnpm license

      - name: Build roblox-ts
        run: pnpm build

      - name: Build rojo
        run: rojo build --output development.rbxl

      - name: Deploy project
        run: mantle deploy
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
          MANTLE_OPEN_CLOUD_API_KEY: ${{ secrets.MANTLE_OPEN_CLOUD_API_KEY }}